# Generated by Django 5.0.1 on 2024-01-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_complaint_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
