# Generated by Django 5.0.1 on 2024-01-17 12:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_complaint_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complain_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
